name: PR Agent Review

on:
  pull_request:
    types: [opened, synchronize] # Trigger on PR open and update

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip3 install -r pr-review-agent/requirements.txt

      - name: Run PR Agent Review
        working-directory: pr-review-agent
        run: python3 main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
