name: PR Agent Review

on:
  pull_request:
    types: [opened, synchronize] # Trigger on PR open and update

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Workspace Contents
        run: |
          pwd
          ls -la
          echo "Root contents:"
          ls -R

      - name: Run PR Agent Review
        uses: klb-alam/pr-review-agent@main # Ensure this points to the correct branch
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.FINE_GRAINED_TOKEN }}
          pr_number: 1

